Repository alkemyTech/OT148-JAVA, pull requests merged in 2022-03, with the labels that each got.

#36 [OT148-47] Endpoint Update News
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/dto/NewsUpdateDTO.java
  src/main/java/com/alkemy/ong/mapper/NewsMapper.java
  src/main/java/com/alkemy/ong/service/NewsService.java
  src/main/resources/application.properties
Labels: enhancement

#35 [OT148-46] Endpoint News Creation
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/service/NewsService.java
  src/main/resources/application.properties
Labels: enhancement

#38 [OT148-50] Create activity
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/ActivityController.java
  src/main/java/com/alkemy/ong/dto/ActivityCreationDTO.java
  src/main/java/com/alkemy/ong/dto/ActivityDTO.java
  src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
  src/main/java/com/alkemy/ong/service/ActivityService.java
Labels: enhancement

#41 [OT148-32] Endpoint Delete User
  src/main/java/com/alkemy/ong/controller/UserController.java
  src/main/java/com/alkemy/ong/service/UserService.java
Labels: enhancement

#40 [OT148-44] Endpoint Delete Categories
  src/main/java/com/alkemy/ong/controller/CategoryController.java
  src/main/java/com/alkemy/ong/service/CategoryService.java
Labels: enhancement

#44 [OT148:53] Contact model and repository
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/domain/Contact.java
  src/main/java/com/alkemy/ong/repository/ContactRepository.java
  src/main/java/com/alkemy/ong/repository/model/ContactModel.java
  src/main/java/com/alkemy/ong/service/ContactService.java
Labels: enhancement

#27 Ot148 31 - Add Logic of JWT
  pom.xml
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/UserController.java
  src/main/java/com/alkemy/ong/domain/Role.java
  src/main/java/com/alkemy/ong/dto/JwtDTO.java
  src/main/java/com/alkemy/ong/mapper/RoleMapper.java
  src/main/java/com/alkemy/ong/repository/RoleRepository.java
  src/main/java/com/alkemy/ong/repository/model/NewsModel.java
  src/main/java/com/alkemy/ong/repository/model/RoleModel.java
  src/main/java/com/alkemy/ong/security/JwtEntryPoint.java
  src/main/java/com/alkemy/ong/security/JwtProvider.java
  src/main/java/com/alkemy/ong/security/JwtTokenFilter.java
  src/main/java/com/alkemy/ong/security/MainUser.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/security/UserDetailsServiceImpl.java
  src/main/java/com/alkemy/ong/util/RoleName.java
  src/main/resources/application.properties
Labels: enhancement

#47 Ot148 51 update activity
  src/main/java/com/alkemy/ong/controller/ActivityController.java
  src/main/java/com/alkemy/ong/dto/ActivityUpdateDTO.java
  src/main/java/com/alkemy/ong/exception/ActivityNotFoundException.java
  src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
  src/main/java/com/alkemy/ong/service/ActivityService.java
Labels: enhancement

#46 [OT148:54] Endpoint store contacts
  src/main/java/com/alkemy/ong/controller/ContactController.java
  src/main/java/com/alkemy/ong/dto/ContactDTO.java
  src/main/java/com/alkemy/ong/mapper/ContactMapper.java
  src/main/java/com/alkemy/ong/service/ContactService.java
Labels: enhancement

#48 [OT148-63] Adding attributes to Organization
  src/main/java/com/alkemy/ong/domain/Organization.java
  src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
  src/main/java/com/alkemy/ong/dto/OrganizationUpdateDTO.java
  src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
  src/main/java/com/alkemy/ong/repository/model/OrganizationModel.java
  src/main/java/com/alkemy/ong/service/OrganizationService.java
Labels: enhancement

#51 [Ot148-61]: Endpoint Contacts List
  src/main/java/com/alkemy/ong/controller/ContactController.java
  src/main/java/com/alkemy/ong/repository/ContactRepository.java
  src/main/java/com/alkemy/ong/service/ContactService.java
Labels: enhancement

#52 [OT148-64] Links of social networks in endpoint of organization
  src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
Labels: enhancement

#49 Ot148 52 seed data activity
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__insertData.sql
Labels: enhancement

#53 [OT148:60] Endpoint slides
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/domain/Organization.java
  src/main/java/com/alkemy/ong/domain/Slide.java
  src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
  src/main/java/com/alkemy/ong/dto/SlideDTO.java
  src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
  src/main/java/com/alkemy/ong/mapper/SlideMapper.java
  src/main/java/com/alkemy/ong/repository/SlideRepository.java
  src/main/java/com/alkemy/ong/repository/model/OrganizationModel.java
  src/main/java/com/alkemy/ong/repository/model/SlideModel.java
  src/main/java/com/alkemy/ong/service/OrganizationService.java
Labels: enhancement

#54 {Ot148 65} Endpoint Creation Testimonial
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/dto/TestimonialCreationDTO.java
  src/main/java/com/alkemy/ong/dto/TestimonialDTO.java
  src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
  src/main/java/com/alkemy/ong/repository/model/TestimonialModel.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/TestimonialService.java
Labels: enhancement

#55 [OT148-68] Endpoint members
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/dto/MemberDTO.java
  src/main/java/com/alkemy/ong/mapper/MemberMapper.java
  src/main/java/com/alkemy/ong/repository/MemberRepository.java
  src/main/java/com/alkemy/ong/service/MemberService.java
Labels: enhancement

#56 [OT148-72] User seed
  README.md
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__insertData.sql
Labels: enhancement

#58 [OT148-56] Slides details
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/exception/SlideNotFoundException.java
  src/main/java/com/alkemy/ong/service/SlideService.java
Labels: enhancement

#57 [OT148-67] DeleteById Endpoint of Testimonial class
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/exception/TestimonialNotFoundException.java
  src/main/java/com/alkemy/ong/repository/model/TestimonialModel.java
  src/main/java/com/alkemy/ong/service/TestimonialService.java
  src/main/resources/application.properties
Labels: enhancement

#59 [OT148-59] Endpoint delete slide
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/service/SlideService.java
Labels: enhancement

#61 [Ot148-57]: Endpoint Slides Creation
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/domain/Organization.java
  src/main/java/com/alkemy/ong/dto/SlideCreationDTO.java
  src/main/java/com/alkemy/ong/mapper/SlideMapper.java
  src/main/java/com/alkemy/ong/repository/SlideRepository.java
  src/main/java/com/alkemy/ong/service/SlideService.java
  src/main/java/com/alkemy/ong/util/Base64DecodedMultiPartFile.java
Labels: enhancement

#64 [Ot148-62]: Email Send Contact
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/service/ContactService.java
  src/main/java/com/alkemy/ong/service/EmailService.java
  src/main/resources/template/plantilla_email_contacto.html
Labels: enhancement

#63 [Ot148-58]: Endpoint Slides Update
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/dto/SlideUpdateDTO.java
  src/main/java/com/alkemy/ong/mapper/SlideMapper.java
  src/main/java/com/alkemy/ong/service/SlideService.java
Labels: enhancement

#65 [OT148-69] Endpoint createMember
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/dto/MemberCreationDTO.java
  src/main/java/com/alkemy/ong/mapper/MemberMapper.java
  src/main/java/com/alkemy/ong/service/MemberService.java
Labels: enhancement

#66 [OT148-33]: Role Validate
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
Labels: enhancement

#69 Ot148 74 comments
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/domain/Comment.java
  src/main/java/com/alkemy/ong/dto/CommentDTO.java
  src/main/java/com/alkemy/ong/mapper/CommentMapper.java
  src/main/java/com/alkemy/ong/repository/CommentRepository.java
  src/main/java/com/alkemy/ong/repository/model/CommentModel.java
  src/main/java/com/alkemy/ong/service/CommentService.java
Labels: enhancement

#71 [OT148-70] Endpoint deleteMember
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/exception/MemberNotFoundException.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/MemberService.java
Labels: enhancement

#72 [OT148:84] Swagger
  README.md
  pom.xml
  src/main/java/com/alkemy/ong/config/SwaggerConfig.java
  src/main/java/com/alkemy/ong/controller/SwaggerController.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
Labels: documentation

#73 [OT148-71] Endpoint UpdateMember
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/dto/MemberUpdateDTO.java
  src/main/java/com/alkemy/ong/mapper/MemberMapper.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/MemberService.java
Labels: enhancement

#74 [OT148-75] Endpoint get comments
  src/main/java/com/alkemy/ong/controller/CommentController.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
  src/main/java/com/alkemy/ong/dto/CommentBodyDTO.java
  src/main/java/com/alkemy/ong/mapper/CommentMapper.java
  src/main/java/com/alkemy/ong/repository/CommentRepository.java
  src/main/java/com/alkemy/ong/repository/model/CommentModel.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/CommentService.java
Labels: enhancement

#75 [Ot148-78]: Endpoint Comment Delete
  src/main/java/com/alkemy/ong/controller/CommentController.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
  src/main/java/com/alkemy/ong/exception/CommentNotFoundException.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/CommentService.java
Labels: enhancement

#77 [OT148-76] Creation comment
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/controller/CommentController.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
  src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
  src/main/java/com/alkemy/ong/mapper/CommentMapper.java
  src/main/java/com/alkemy/ong/security/MainUser.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/service/CommentService.java
Labels: enhancement

#79 OT148-77: Update Comment
  src/main/java/com/alkemy/ong/controller/CommentController.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
  src/main/java/com/alkemy/ong/dto/CommentBodyDTO.java
  src/main/java/com/alkemy/ong/exception/OperationNotPermittedException.java
  src/main/java/com/alkemy/ong/mapper/CommentMapper.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/main/java/com/alkemy/ong/security/SecurityUtils.java
  src/main/java/com/alkemy/ong/service/CommentService.java
Labels: enhancement

#76 [OT148-82] Adding pagination to Members
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/dto/MemberListDTO.java
  src/main/java/com/alkemy/ong/repository/MemberRepository.java
  src/main/java/com/alkemy/ong/service/MemberService.java
  src/main/java/com/alkemy/ong/util/ContextUtils.java
Labels: enhancement

#78 Ot148 80 pagination category
  src/main/java/com/alkemy/ong/controller/CategoryController.java
  src/main/java/com/alkemy/ong/dto/PageDTO.java
  src/main/java/com/alkemy/ong/repository/CategoryRepository.java
  src/main/java/com/alkemy/ong/service/CategoryService.java
Labels: enhancement

#82 [Ot148-81]: Add News Pagination
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/dto/NewsListDTO.java
  src/main/java/com/alkemy/ong/repository/NewsRepository.java
  src/main/java/com/alkemy/ong/service/NewsService.java
Labels: enhancement

#83 [OT148-89] Authentication documentation
  pom.xml
  src/main/java/com/alkemy/ong/controller/UserController.java
  src/main/java/com/alkemy/ong/controller/impl/UserResource.java
Labels: documentation

#85 [OT148-87] Adding swagger documentation to MemberController
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/controller/impl/MemberResource.java
Labels: documentation

#86 [OT148-100] Changes various controllers
  src/main/java/com/alkemy/ong/controller/ActivityController.java
  src/main/java/com/alkemy/ong/controller/CategoryController.java
  src/main/java/com/alkemy/ong/controller/ContactController.java
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/controller/OrganizationController.java
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/controller/impl/ActivityResource.java
  src/main/java/com/alkemy/ong/controller/impl/CategoryResource.java
  src/main/java/com/alkemy/ong/controller/impl/ContactResource.java
  src/main/java/com/alkemy/ong/controller/impl/MemberResource.java
  src/main/java/com/alkemy/ong/controller/impl/NewsResource.java
  src/main/java/com/alkemy/ong/controller/impl/OrganizationResource.java
  src/main/java/com/alkemy/ong/controller/impl/SlideResource.java
  src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
Labels: enhancement

#87 [OT148-86]: Add News Documentation
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/controller/impl/NewsResource.java
Labels: documentation

#81 {Ot148 88} Add Documentation Testimonials
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
Labels: documentation

#80 {Ot148 83} Add pages Testimonials
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
  src/main/java/com/alkemy/ong/dto/TestimonialListDTO.java
  src/main/java/com/alkemy/ong/repository/TestimonialRepository.java
  src/main/java/com/alkemy/ong/service/TestimonialService.java
Labels: enhancement

#92 [OT148-97] Get test Categories
  src/test/java/com/alkemy/ong/.gitkeep
  src/test/java/com/alkemy/ong/CategoryControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/util/HeaderBuilder.java
  src/test/java/com/alkemy/ong/util/JwtUtil.java
  src/test/resources/application-test.properties
Labels: enhancement

#90 [OT148-91] Test: Endpoint/members
  src/test/java/com/alkemy/ong/CategoryControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/MemberControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/util/HeaderBuilder.java
  src/test/java/com/alkemy/ong/util/JwtUtil.java
  src/test/resources/application-test.properties
Labels: enhancement

#94 [OT148-94] Adding ActivityControllerFunctionalTest
  src/test/java/com/alkemy/ong/ActivityControllerFunctionalTest.java
Labels: testing

#96 [OT148-103]: Fix User Login Exception
  src/main/java/com/alkemy/ong/controller/UserController.java
  src/main/java/com/alkemy/ong/controller/impl/UserResource.java
  src/main/java/com/alkemy/ong/exception/WrongValuesException.java
  src/main/java/com/alkemy/ong/service/UserService.java
Labels: enhancement

#95 [OT148-96] Test endpoint authentication
  src/test/java/com/alkemy/ong/UserControllerFuncionalTest.java
Labels: testing

#99 [OT148-102]: Test Endpoint Comments
  src/test/java/com/alkemy/ong/CommentControllerFunctionalTest.java
Labels: testing

#100 [OT148-26]: Endpoints Access Validation By Role
  src/main/java/com/alkemy/ong/config/AppConfig.java
  src/main/java/com/alkemy/ong/security/JwtProvider.java
  src/main/resources/application.properties
Labels: enhancement

#103 [OT148-105] add information in readme
  README.md
Labels: documentation

#104 {Ot 148 95 } Test endpoint Contact
  src/main/java/com/alkemy/ong/controller/ContactController.java
  src/main/resources/application.properties
  src/test/java/com/alkemy/ong/ContactControllerFunctionalTest.java
  src/test/resources/application-test.properties
Labels: enhancement

#101 {Ot148 98} Testimonial Controller Test
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
  src/main/java/com/alkemy/ong/dto/TestimonialCreationDTO.java
  src/main/java/com/alkemy/ong/dto/TestimonialDTO.java
  src/main/java/com/alkemy/ong/dto/TestimonialListDTO.java
  src/main/java/com/alkemy/ong/security/SecurityConfig.java
  src/test/java/com/alkemy/ong/TestimonialControllerFunctionalTest.java
Labels: enhancement

#106 [OT148]: Added a Description to Testimonials
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
Labels: documentation

#107 [OT148]: Added Organizations Documentation
  src/main/java/com/alkemy/ong/controller/OrganizationController.java
  src/main/java/com/alkemy/ong/controller/impl/OrganizationResource.java
Labels: documentation

#105 [OT148] Added documentation activity
  src/main/java/com/alkemy/ong/controller/ActivityController.java
  src/main/java/com/alkemy/ong/controller/CategoryController.java
  src/main/java/com/alkemy/ong/controller/impl/ActivityResource.java
Labels: documentation

#108 [148] Added Slides Documentation
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/controller/impl/SlideResource.java
Labels: documentation

#102 [OT148-101] Creation of ExceptionHandler
  src/main/java/com/alkemy/ong/controller/ActivityController.java
  src/main/java/com/alkemy/ong/controller/CategoryController.java
  src/main/java/com/alkemy/ong/controller/NewsController.java
  src/main/java/com/alkemy/ong/controller/OrganizationController.java
  src/main/java/com/alkemy/ong/controller/SlideController.java
  src/main/java/com/alkemy/ong/controller/TestimonialController.java
  src/main/java/com/alkemy/ong/controller/UserController.java
  src/main/java/com/alkemy/ong/controller/impl/ActivityResource.java
  src/main/java/com/alkemy/ong/controller/impl/CategoryResource.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
  src/main/java/com/alkemy/ong/controller/impl/ContactResource.java
  src/main/java/com/alkemy/ong/controller/impl/MemberResource.java
  src/main/java/com/alkemy/ong/controller/impl/NewsResource.java
  src/main/java/com/alkemy/ong/controller/impl/OrganizationResource.java
  src/main/java/com/alkemy/ong/controller/impl/SlideResource.java
  src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
  src/main/java/com/alkemy/ong/controller/impl/UserResource.java
  src/main/java/com/alkemy/ong/dto/ErrorDTO.java
  src/main/java/com/alkemy/ong/exception/ActivityNotFoundException.java
  src/main/java/com/alkemy/ong/exception/ApiErrorDTO.java
  src/main/java/com/alkemy/ong/exception/BadRequestException.java
  src/main/java/com/alkemy/ong/exception/CategoryNotFoundException.java
  src/main/java/com/alkemy/ong/exception/CommentNotFoundException.java
  src/main/java/com/alkemy/ong/exception/DuplicateEmailException.java
  src/main/java/com/alkemy/ong/exception/GlobalExceptionHandler.java
  src/main/java/com/alkemy/ong/exception/InvalidPasswordException.java
  src/main/java/com/alkemy/ong/exception/MemberNotFoundException.java
  src/main/java/com/alkemy/ong/exception/NewsNotFoundException.java
  src/main/java/com/alkemy/ong/exception/OngRequestException.java
  src/main/java/com/alkemy/ong/exception/OperationNotPermittedException.java
  src/main/java/com/alkemy/ong/exception/OrganizationNotFoundException.java
  src/main/java/com/alkemy/ong/exception/SlideNotFoundException.java
  src/main/java/com/alkemy/ong/exception/TestimonialNotFoundException.java
  src/main/java/com/alkemy/ong/exception/UserNotFoundException.java
  src/main/java/com/alkemy/ong/exception/WrongValuesException.java
  src/main/java/com/alkemy/ong/service/ActivityService.java
  src/main/java/com/alkemy/ong/service/CategoryService.java
  src/main/java/com/alkemy/ong/service/CommentService.java
  src/main/java/com/alkemy/ong/service/MemberService.java
  src/main/java/com/alkemy/ong/service/NewsService.java
  src/main/java/com/alkemy/ong/service/OrganizationService.java
  src/main/java/com/alkemy/ong/service/SlideService.java
  src/main/java/com/alkemy/ong/service/TestimonialService.java
  src/main/java/com/alkemy/ong/service/UserService.java
  src/test/java/com/alkemy/ong/ActivityControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/CategoryControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/CommentControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/ContactControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/MemberControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/NewsControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/OrganizationControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/TestimonialControllerFunctionalTest.java
  src/test/java/com/alkemy/ong/UserControllerFuncionalTest.java
Labels: enhancement

#110 [OT148-memberDoc] Creating Comments documentation and fix member documentation
  src/main/java/com/alkemy/ong/controller/CommentController.java
  src/main/java/com/alkemy/ong/controller/MemberController.java
  src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
Labels: documentation
